spring:
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassNam: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://129.204.89.200:3306/bgxx
    username: wenxi
    password: 123456

  #视图解析器
  #mvc:
   # view:
    #  prefix: /WEB-INF/jsp/
    #  suffix: .jsp
#mybatis 配置映射文件
#mybatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml
